import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import ThemeProvider, { ThemeMode } from "@/context/theme";
import { BackgroundCover, Navbar } from "@/components";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  const defaultThemeMode = cookies().get("mode")?.value as ThemeMode | undefined;

  return (
    <html lang="en">
    <body className={inter.className} data-theme={defaultThemeMode}>
    <ThemeProvider defaultThemeMode={defaultThemeMode}>
      <BackgroundCover />
      <Navbar />
      {children}
    </ThemeProvider>
    </body>
    </html>
  );
}
